import PptxGenJS from 'pptxgenjs';
import { PresentationItem, SlideItem, PresentationStyle } from '@/lib/types';

interface ThemeConfig {
  bg: string;
  titleColor: string;
  bodyColor: string;
  accentColor: string;
  cardBg: string;
  cardBorder: string;
  fontFace: string;
}

const THEME_MAP: Record<PresentationStyle, ThemeConfig> = {
  Academic: {
    bg: 'F8FAFC',
    titleColor: '1E1B4B',
    bodyColor: '334155',
    accentColor: '7C3AED',
    cardBg: 'FFFFFF',
    cardBorder: 'E2E8F0',
    fontFace: 'Georgia',
  },
  Corporate: {
    bg: '0F172A',
    titleColor: 'FFFFFF',
    bodyColor: 'E2E8F0',
    accentColor: '38BDF8',
    cardBg: '1E293B',
    cardBorder: '334155',
    fontFace: 'Arial',
  },
  Minimal: {
    bg: 'FFFFFF',
    titleColor: '0F172A',
    bodyColor: '475569',
    accentColor: '64748B',
    cardBg: 'F8FAFC',
    cardBorder: 'E2E8F0',
    fontFace: 'Calibri',
  },
  Technical: {
    bg: '0B0F19',
    titleColor: 'A78BFA',
    bodyColor: 'CBD5E1',
    accentColor: '22D3EE',
    cardBg: '131B2E',
    cardBorder: '1E293B',
    fontFace: 'Consolas',
  },
  'Project Viva': {
    bg: '1E1035',
    titleColor: 'F5F3FF',
    bodyColor: 'DDD6FE',
    accentColor: 'C084FC',
    cardBg: '2E1A4E',
    cardBorder: '4C1D95',
    fontFace: 'Trebuchet MS',
  },
};

export async function exportPresentationToPptx(
  presentation: PresentationItem,
  fileName?: string
): Promise<void> {
  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_16x9'; // 13.33 x 7.5 inches
  pptx.title = presentation.title || 'EasyDoc Presentation';
  pptx.author = 'EasyDoc AI Studio';
  pptx.company = 'EasyDoc Document Platform';

  const theme = THEME_MAP[presentation.style] || THEME_MAP['Academic'];
  const slides = Array.isArray(presentation.slides) ? presentation.slides : [];

  slides.forEach((slideData: SlideItem, index: number) => {
    const slide = pptx.addSlide();
    slide.background = { color: theme.bg };

    const isFirstSlide = index === 0 || slideData.layout === 'title';
    const isConclusion = slideData.layout === 'conclusion';
    const bullets = Array.isArray(slideData.bullets) ? slideData.bullets : [];

    if (isFirstSlide) {
      // Title slide layout
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.8,
        y: 0.8,
        w: 11.7,
        h: 5.8,
        fill: { color: theme.cardBg },
        line: { color: theme.accentColor, width: 2 },
        rectRadius: 0.2,
      });

      // EasyDoc watermark tag
      slide.addText('EASYDOC AI • KEYNOTE STUDIO', {
        x: 1.2,
        y: 1.2,
        w: 10.5,
        h: 0.4,
        fontSize: 12,
        bold: true,
        color: theme.accentColor,
        fontFace: theme.fontFace,
      });

      // Main Title
      slide.addText(slideData.title || presentation.title || 'Executive Presentation', {
        x: 1.2,
        y: 1.8,
        w: 10.5,
        h: 2.2,
        fontSize: 32,
        bold: true,
        color: theme.titleColor,
        fontFace: theme.fontFace,
        valign: 'middle',
      });

      // Subtitle or bullets summary
      const textContent = slideData.subtitle || (bullets.length > 0 ? bullets.join('   •   ') : 'Professional Presentation Deck');
      slide.addText(textContent, {
        x: 1.2,
        y: 4.2,
        w: 10.5,
        h: 1.2,
        fontSize: 15,
        color: theme.bodyColor,
        fontFace: theme.fontFace,
      });

      // Footer badge
      slide.addText(`Theme: ${presentation.style}  |  Generated by EasyDoc Cyber Studio`, {
        x: 1.2,
        y: 5.8,
        w: 10.5,
        h: 0.4,
        fontSize: 10,
        color: theme.bodyColor,
        fontFace: theme.fontFace,
      });
    } else if (isConclusion) {
      // Conclusion Slide
      slide.addShape(pptx.ShapeType.rect, {
        x: 1.0,
        y: 0.8,
        w: 11.3,
        h: 5.8,
        fill: { color: theme.cardBg },
        line: { color: theme.accentColor, width: 2 },
        rectRadius: 0.2,
      });

      slide.addText('SUMMARY & TECHNICAL Q&A', {
        x: 1.5,
        y: 1.2,
        w: 10.3,
        h: 0.4,
        fontSize: 13,
        bold: true,
        color: theme.accentColor,
        fontFace: theme.fontFace,
      });

      slide.addText(slideData.title || 'Conclusion & Key Takeaways', {
        x: 1.5,
        y: 1.7,
        w: 10.3,
        h: 1.0,
        fontSize: 26,
        bold: true,
        color: theme.titleColor,
        fontFace: theme.fontFace,
      });

      if (bullets.length > 0) {
        const bulletItems = bullets.map((b) => ({
          text: b,
          options: {
            fontSize: 15,
            color: theme.bodyColor,
            bullet: true,
            breakLine: true,
            paraSpaceAfter: 12,
            fontFace: theme.fontFace,
          },
        }));

        slide.addText(bulletItems, {
          x: 1.5,
          y: 2.8,
          w: 10.3,
          h: 3.2,
          valign: 'top',
        });
      }
    } else {
      // Standard Content Slide
      // Top header banner
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.8,
        y: 0.5,
        w: 11.7,
        h: 1.0,
        fill: { color: theme.cardBg },
        line: { color: theme.cardBorder, width: 1 },
        rectRadius: 0.1,
      });

      // Slide Title
      slide.addText(`${slideData.slideNumber || index + 1}. ${slideData.title || 'Key Focus'}`, {
        x: 1.1,
        y: 0.6,
        w: 10.5,
        h: 0.8,
        fontSize: 20,
        bold: true,
        color: theme.titleColor,
        fontFace: theme.fontFace,
        valign: 'middle',
      });

      // Content Card
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.8,
        y: 1.7,
        w: 11.7,
        h: 5.0,
        fill: { color: theme.cardBg },
        line: { color: theme.cardBorder, width: 1 },
        rectRadius: 0.15,
      });

      // Subtitle if available
      if (slideData.subtitle) {
        slide.addText(slideData.subtitle, {
          x: 1.2,
          y: 1.9,
          w: 11.0,
          h: 0.5,
          fontSize: 13,
          italic: true,
          color: theme.accentColor,
          fontFace: theme.fontFace,
        });
      }

      // Bullet points
      if (bullets.length > 0) {
        const bulletObjects = bullets.map((bullet) => ({
          text: bullet,
          options: {
            fontSize: 15,
            color: theme.bodyColor,
            bullet: true,
            breakLine: true,
            paraSpaceAfter: 12,
            fontFace: theme.fontFace,
          },
        }));

        slide.addText(bulletObjects, {
          x: 1.2,
          y: slideData.subtitle ? 2.5 : 2.1,
          w: 11.0,
          h: 4.0,
          valign: 'top',
        });
      }

      // Footer Slide number
      slide.addText(`Slide ${index + 1} of ${slides.length}`, {
        x: 9.8,
        y: 6.8,
        w: 2.5,
        h: 0.3,
        fontSize: 9,
        color: theme.bodyColor,
        fontFace: theme.fontFace,
        align: 'right',
      });
    }

    // Add speaker notes if present
    if (slideData.notes) {
      slide.addNotes(slideData.notes);
    }
  });

  const finalName = (fileName || presentation.title || 'EasyDoc_Presentation')
    .replace(/[^a-zA-Z0-9_-]/g, '_')
    .concat('.pptx');

  await pptx.writeFile({ fileName: finalName });
}
