import PptxGenJS from 'pptxgenjs';
import { PresentationItem, SlideItem, PresentationStyle } from '@/lib/types';


interface ThemeConfig {
  bg: string;
  titleColor: string;
  bodyColor: string;
  accentColor: string;
  cardBg: string;
  fontFace: string;
}

const THEME_MAP: Record<PresentationStyle, ThemeConfig> = {
  Academic: {
    bg: 'F8FAFC',
    titleColor: '1E1B4B',
    bodyColor: '334155',
    accentColor: '7C3AED',
    cardBg: 'FFFFFF',
    fontFace: 'Georgia',
  },
  Corporate: {
    bg: '0F172A',
    titleColor: 'FFFFFF',
    bodyColor: 'E2E8F0',
    accentColor: '38BDF8',
    cardBg: '1E293B',
    fontFace: 'Arial',
  },
  Minimal: {
    bg: 'FFFFFF',
    titleColor: '0F172A',
    bodyColor: '475569',
    accentColor: '64748B',
    cardBg: 'F1F5F9',
    fontFace: 'Calibri',
  },
  Technical: {
    bg: '0B0F19',
    titleColor: 'A78BFA',
    bodyColor: 'CBD5E1',
    accentColor: '22D3EE',
    cardBg: '131B2E',
    fontFace: 'Consolas',
  },
  'Project Viva': {
    bg: '1E1035',
    titleColor: 'F5F3FF',
    bodyColor: 'DDD6FE',
    accentColor: 'C084FC',
    cardBg: '2E1A4E',
    fontFace: 'Trebuchet MS',
  },
};

export async function exportPresentationToPptx(
  presentation: PresentationItem,
  fileName?: string
): Promise<void> {
  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_16x9';
  pptx.title = presentation.title || 'EasyDoc Presentation';
  pptx.author = 'EasyDoc AI Studio';
  pptx.company = 'EasyDoc Document Platform';




  const theme = THEME_MAP[presentation.style] || THEME_MAP['Academic'];

  presentation.slides.forEach((slideData: SlideItem, index: number) => {
    const slide = pptx.addSlide();
    slide.background = { color: theme.bg };

    const isFirstSlide = index === 0 || slideData.layout === 'title';
    const isConclusion = slideData.layout === 'conclusion';

    if (isFirstSlide) {
      // Title slide layout
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.8,
        y: 1.0,
        w: 11.7,
        h: 5.5,
        fill: { color: theme.cardBg },
        line: { color: theme.accentColor, width: 2 },
        rectRadius: 0.2,
      });

      // EasyDoc watermark tag
      slide.addText('EASYDOC AI • PRESENTATION STUDIO', {
        x: 1.2,
        y: 1.4,
        w: 10.0,
        h: 0.4,
        fontSize: 12,
        bold: true,
        color: theme.accentColor,
        fontFace: theme.fontFace,
      });

      // Main Title
      slide.addText(slideData.title || presentation.title, {
        x: 1.2,
        y: 2.0,
        w: 10.5,
        h: 2.0,
        fontSize: 34,
        bold: true,
        color: theme.titleColor,
        fontFace: theme.fontFace,
        valign: 'middle',
      });

      // Subtitle / Bullets
      if (slideData.subtitle || slideData.bullets.length > 0) {
        const textContent = slideData.subtitle || slideData.bullets.join('  •  ');
        slide.addText(textContent, {
          x: 1.2,
          y: 4.2,
          w: 10.5,
          h: 1.2,
          fontSize: 16,
          color: theme.bodyColor,
          fontFace: theme.fontFace,
        });
      }

      // Footer badge
      slide.addText(`Style: ${presentation.style}  |  Generated by EasyDoc`, {
        x: 1.2,
        y: 5.8,
        w: 10.5,
        h: 0.4,
        fontSize: 10,
        color: theme.bodyColor,
        fontFace: theme.fontFace,
      });
    } else if (isConclusion) {
      // Conclusion Slide
      slide.addShape(pptx.ShapeType.rect, {
        x: 1.5,
        y: 1.2,
        w: 10.3,
        h: 5.0,
        fill: { color: theme.cardBg },
        line: { color: theme.accentColor, width: 2 },
        rectRadius: 0.2,
      });

      slide.addText('SUMMARY & CONCLUSION', {
        x: 2.0,
        y: 1.6,
        w: 9.3,
        h: 0.5,
        fontSize: 14,
        bold: true,
        color: theme.accentColor,
        fontFace: theme.fontFace,
      });

      slide.addText(slideData.title, {
        x: 2.0,
        y: 2.2,
        w: 9.3,
        h: 1.0,
        fontSize: 26,
        bold: true,
        color: theme.titleColor,
        fontFace: theme.fontFace,
      });

      const bulletItems = slideData.bullets.map((b) => ({
        text: b,
        options: {
          fontSize: 16,
          color: theme.bodyColor,
          bullet: true,
          breakLine: true,
          fontFace: theme.fontFace,
        },
      }));

      if (bulletItems.length > 0) {
        slide.addText(bulletItems, {
          x: 2.0,
          y: 3.3,
          w: 9.3,
          h: 2.4,
          valign: 'top',
        });
      }
    } else {
      // Standard Content Slide
      // Top header bar
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.8,
        y: 0.5,
        w: 11.7,
        h: 1.0,
        fill: { color: theme.cardBg },
        line: { color: theme.accentColor, width: 1 },
        rectRadius: 0.1,
      });

      // Slide Title
      slide.addText(`${slideData.slideNumber || index + 1}. ${slideData.title}`, {
        x: 1.1,
        y: 0.6,
        w: 10.0,
        h: 0.8,
        fontSize: 22,
        bold: true,
        color: theme.titleColor,
        fontFace: theme.fontFace,
        valign: 'middle',
      });

      // Content Card
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.8,
        y: 1.7,
        w: 11.7,
        h: 4.8,
        fill: { color: theme.cardBg },
        line: { color: theme.accentColor, width: 1 },
        rectRadius: 0.15,
      });

      // Bullet points
      if (slideData.bullets && slideData.bullets.length > 0) {
        const bulletObjects = slideData.bullets.map((bullet) => ({
          text: bullet,
          options: {
            fontSize: 16,
            color: theme.bodyColor,
            bullet: true,
            breakLine: true,
            paraSpaceAfter: 10,
            fontFace: theme.fontFace,
          },
        }));


        slide.addText(bulletObjects, {
          x: 1.2,
          y: 2.0,
          w: 11.0,
          h: 4.2,
          valign: 'top',
        });
      } else if (slideData.subtitle) {
        slide.addText(slideData.subtitle, {
          x: 1.2,
          y: 2.0,
          w: 11.0,
          h: 4.2,
          fontSize: 18,
          color: theme.bodyColor,
          fontFace: theme.fontFace,
          valign: 'top',
        });
      }

      // Footer Slide number
      slide.addText(`Slide ${index + 1} of ${presentation.slides.length}`, {
        x: 10.0,
        y: 6.8,
        w: 2.5,
        h: 0.3,
        fontSize: 9,
        color: theme.bodyColor,
        fontFace: theme.fontFace,
        align: 'right',
      });
    }

    // Add speaker notes if present
    if (slideData.notes) {
      slide.addNotes(slideData.notes);
    }
  });

  const finalName = (fileName || presentation.title || 'EasyDoc_Presentation')
    .replace(/[^a-zA-Z0-9_-]/g, '_')
    .concat('.pptx');

  await pptx.writeFile({ fileName: finalName });
}
