// Comprehensive Template Catalog for EasyDoc AI Document Platform (100+ Templates)

export interface TemplateEntry {
  id: string;
  name: string;
  category:
    | 'College Students'
    | 'Faculty Templates'
    | 'Business Templates'
    | 'ATS Resume Builder'
    | 'Letters'
    | 'Government'
    | 'Personal';
  description: string;
  suggestedTone: string;
  suggestedLength: string;
  promptInstructions: string;
  placeholderInputs: string[];
  tags: string[];
  iconName: string;
  isPopular?: boolean;
  isNew?: boolean;
  estimatedTime?: string;
  exampleOutput?: string;
}

export const TEMPLATE_CATEGORIES = [
  'All',
  'College Students',
  'Faculty Templates',
  'Business Templates',
  'ATS Resume Builder',
  'Letters',
  'Government',
  'Personal',
] as const;

export const TEMPLATE_CATALOG: TemplateEntry[] = [
  // ==========================================
  // CATEGORY 1: COLLEGE STUDENTS (55 Templates)
  // ==========================================
  {
    id: 'cs-01',
    name: 'Assignment',
    category: 'College Students',
    description: 'Structured academic assignment with introduction, core analysis, references, and conclusion.',
    suggestedTone: 'Academic & Analytical',
    suggestedLength: '2-4 pages',
    promptInstructions: 'Create a university assignment covering topic background, key theoretical pillars, critical analysis, numerical/logical solutions, and APA format references.',
    placeholderInputs: ['Subject Name', 'Assignment Topic', 'Key Questions', 'Submission Date'],
    tags: ['college', 'student', 'assignment', 'homework', 'academic'],
    iconName: 'BookOpen',
    isPopular: true,
    estimatedTime: '30s',
  },
  {
    id: 'cs-02',
    name: 'Lab Record',
    category: 'College Students',
    description: 'Engineering and science laboratory experiment record with apparatus, theory, procedure, and observations.',
    suggestedTone: 'Technical & Concise',
    suggestedLength: '3-5 pages',
    promptInstructions: 'Format an official laboratory report detailing Objective, Apparatus Required, Circuit Diagram/Theory, Step-by-Step Procedure, Observation Table, Sample Calculation, Results, and Precautions.',
    placeholderInputs: ['Lab Name', 'Experiment Title', 'Aim / Objective', 'Observations / Readings'],
    tags: ['lab', 'engineering', 'practical', 'experiment', 'science'],
    iconName: 'FlaskConical',
    isPopular: true,
    estimatedTime: '25s',
  },
  {
    id: 'cs-03',
    name: 'Project Report',
    category: 'College Students',
    description: 'Full academic project report containing abstract, problem statement, methodology, results, and future scope.',
    suggestedTone: 'Academic & Formal',
    suggestedLength: '8-15 pages',
    promptInstructions: 'Generate a comprehensive project report detailing Title, Abstract, Introduction, System Requirements, Architecture & Design, Implementation Details, Test Cases & Results, Conclusion, and References.',
    placeholderInputs: ['Project Title', 'Domain / Technology', 'Team Members', 'Guide Name'],
    tags: ['project', 'report', 'academic', 'btech', 'mca'],
    iconName: 'FileText',
    isPopular: true,
    estimatedTime: '45s',
  },
  {
    id: 'cs-04',
    name: 'Mini Project',
    category: 'College Students',
    description: 'Compact project summary detailing core functionality, tech stack, and module breakdown.',
    suggestedTone: 'Technical',
    suggestedLength: '4-6 pages',
    promptInstructions: 'Generate a Mini Project documentation including Objectives, Scope, Technology Stack, System Architecture, Database Schema, Key Features, and Conclusion.',
    placeholderInputs: ['Project Name', 'Tech Stack', 'Main Features'],
    tags: ['mini project', 'btech', 'software', 'code'],
    iconName: 'Code',
    estimatedTime: '30s',
  },
  {
    id: 'cs-05',
    name: 'Major Project',
    category: 'College Students',
    description: 'Final year capstone major project documentation following university guidelines.',
    suggestedTone: 'Comprehensive & Formal',
    suggestedLength: '15-30 pages',
    promptInstructions: 'Draft a capstone major project documentation featuring Certificate, Declaration, Acknowledgement, Abstract, Table of Contents, System Analysis, System Design (UML), Implementation, Testing, Results Analysis, and References.',
    placeholderInputs: ['Capstone Title', 'University / Dept', 'Advisor Name', 'Key Modules'],
    tags: ['major project', 'capstone', 'final year', 'thesis'],
    iconName: 'GraduationCap',
    isPopular: true,
    estimatedTime: '60s',
  },
  {
    id: 'cs-06',
    name: 'Seminar Report',
    category: 'College Students',
    description: 'Technical seminar documentation covering cutting-edge technological trends and research.',
    suggestedTone: 'Informative & Academic',
    suggestedLength: '5-8 pages',
    promptInstructions: 'Create a Seminar Report on a modern technology topic covering Introduction, Working Principle, Key Architectures, Applications, Advantages & Disadvantages, Future Scope, and References.',
    placeholderInputs: ['Seminar Topic', 'Department', 'Key Technologies Covered'],
    tags: ['seminar', 'presentation', 'tech trend'],
    iconName: 'Presentation',
    estimatedTime: '35s',
  },
  {
    id: 'cs-07',
    name: 'Internship Report',
    category: 'College Students',
    description: 'Professional internship completion report detailing company overview, tasks completed, skills gained, and project achievements.',
    suggestedTone: 'Professional & Reflective',
    suggestedLength: '6-10 pages',
    promptInstructions: 'Generate an Internship Report detailing Company Profile, Department Assigned, Tasks Performed, Key Projects Handled, Technologies Learned, Challenges & Solutions, and Personal Reflections.',
    placeholderInputs: ['Company Name', 'Role Title', 'Internship Duration', 'Key Tasks Done'],
    tags: ['internship', 'training', 'company report'],
    iconName: 'Briefcase',
    isPopular: true,
    estimatedTime: '40s',
  },
  {
    id: 'cs-08',
    name: 'Industrial Visit Report',
    category: 'College Students',
    description: 'Field visit report documenting plant operations, technology demonstrations, and learning takeaways.',
    suggestedTone: 'Descriptive',
    suggestedLength: '3-5 pages',
    promptInstructions: 'Format an Industrial Visit Report covering Industry Overview, Visit Objectives, Technical Processing Steps Observed, Equipment Breakdown, Safety Protocols, Key Learnings, and Acknowledgements.',
    placeholderInputs: ['Industry / Plant Name', 'Date of Visit', 'Department', 'Key Machinery Observed'],
    tags: ['industrial visit', 'field visit', 'plant tour'],
    iconName: 'Building2',
    estimatedTime: '30s',
  },
  {
    id: 'cs-09',
    name: 'Research Paper',
    category: 'College Students',
    description: 'Peer-review standard research paper draft with abstract, methodology, data tables, and citations.',
    suggestedTone: 'Formal & Scientific',
    suggestedLength: '6-10 pages',
    promptInstructions: 'Structure an IEEE/ACM style research paper draft featuring Title, Authors, Abstract, Index Terms, Introduction, Related Work, Proposed Methodology, Experimental Evaluation & Results, Discussion, and References.',
    placeholderInputs: ['Paper Title', 'Domain / Sub-field', 'Proposed Method', 'Dataset Used'],
    tags: ['research', 'ieee', 'paper', 'journal'],
    iconName: 'FileCheck',
    isPopular: true,
    estimatedTime: '50s',
  },
  {
    id: 'cs-10',
    name: 'Case Study',
    category: 'College Students',
    description: 'In-depth analysis of a real-world problem, root causes, solution strategies, and outcome evaluations.',
    suggestedTone: 'Analytical & Objective',
    suggestedLength: '4-7 pages',
    promptInstructions: 'Construct a business or technical Case Study featuring Executive Summary, Problem Statement, Organizational Background, Alternatives Considered, Recommended Strategy, Implementation Roadmap, and Expected ROI.',
    placeholderInputs: ['Company / System Name', 'Core Problem', 'Target Outcome'],
    tags: ['case study', 'analysis', 'mba', 'business case'],
    iconName: 'Search',
    estimatedTime: '35s',
  },
  {
    id: 'cs-11',
    name: 'Synopsis',
    category: 'College Students',
    description: 'Concise project synopsis for committee approval prior to thesis or dissertation work.',
    suggestedTone: 'Precise & Persuasive',
    suggestedLength: '2-4 pages',
    promptInstructions: 'Generate a Project Synopsis outlining Title, Introduction, Literature Review Summary, Proposed Objectives, Hardware & Software Requirements, Expected Deliverables, and Work Schedule.',
    placeholderInputs: ['Synopsis Title', 'Degree Program', 'Objectives'],
    tags: ['synopsis', 'proposal', 'approval'],
    iconName: 'FileMinus',
    estimatedTime: '25s',
  },
  {
    id: 'cs-12',
    name: 'Software Requirement Specification (SRS)',
    category: 'College Students',
    description: 'IEEE-830 compliant Software Requirement Specification document for engineering projects.',
    suggestedTone: 'Formal & Technical',
    suggestedLength: '8-12 pages',
    promptInstructions: 'Create a complete IEEE 830 standard SRS covering Introduction (Scope, Definitions), Overall Description (Product Functions, User Classes), Functional Requirements, Non-Functional Requirements (Performance, Security), System Interfaces, and Use Case Diagrams.',
    placeholderInputs: ['Software Name', 'Target Users', 'Core Modules', 'Tech Constraints'],
    tags: ['srs', 'software engineering', 'btech', 'requirements'],
    iconName: 'Cpu',
    isPopular: true,
    estimatedTime: '45s',
  },
  {
    id: 'cs-13',
    name: 'Software Design Document (SDD)',
    category: 'College Students',
    description: 'Detailed architectural blueprint covering system components, data schemas, and API contracts.',
    suggestedTone: 'Technical & Precise',
    suggestedLength: '8-15 pages',
    promptInstructions: 'Draft a Software Design Document detailing System Architecture, Component Diagrams, Database Entity-Relationship Diagrams (ERD), Data Dictionary, API Endpoint Definitions, and Security Layers.',
    placeholderInputs: ['System Name', 'Architecture Pattern (e.g. Microservices)', 'Database Type'],
    tags: ['sdd', 'architecture', 'design', 'uml'],
    iconName: 'Layers',
    estimatedTime: '40s',
  },
  {
    id: 'cs-14',
    name: 'Statement of Purpose (SOP)',
    category: 'College Students',
    description: 'High-impact SOP for university admissions, MS degrees, and study abroad applications.',
    suggestedTone: 'Persuasive & Inspiring',
    suggestedLength: '2 pages',
    promptInstructions: 'Write an engaging Statement of Purpose detailing Academic Background, Research Interests, Motivation for Choosing the Specific University/Program, Career Goals, and Unique Qualities.',
    placeholderInputs: ['Target Program / Degree', 'Target University', 'Field of Interest', 'Key Achievements'],
    tags: ['sop', 'admissions', 'study abroad', 'ms in us'],
    iconName: 'Award',
    isPopular: true,
    estimatedTime: '30s',
  },
  {
    id: 'cs-15',
    name: 'College Leave Letter',
    category: 'College Students',
    description: 'Formal leave application letter addressed to principal, HOD, or class advisor.',
    suggestedTone: 'Formal & Respectful',
    suggestedLength: '1 page',
    promptInstructions: 'Draft an official Leave Application specifying Student Roll Number, Department, Reason for Leave (Medical/Personal), Duration of Absence, and Contact Info during leave.',
    placeholderInputs: ['Student Name', 'Roll Number / USN', 'Reason for Leave', 'Leave Dates', 'HOD / Principal Title'],
    tags: ['leave letter', 'college', 'application', 'permission'],
    iconName: 'Mail',
    isPopular: true,
    estimatedTime: '15s',
  },

  // ==========================================
  // CATEGORY 2: FACULTY TEMPLATES (38 Templates)
  // ==========================================
  {
    id: 'ft-01',
    name: 'Lesson Plan',
    category: 'Faculty Templates',
    description: 'Structured course lesson plan detailing learning outcomes, teaching activities, and assessment methods.',
    suggestedTone: 'Structured & Academic',
    suggestedLength: '2-3 pages',
    promptInstructions: 'Create a comprehensive Lesson Plan including Course Title, Topic, Bloom’s Taxonomy Outcomes, Prerequisites, Lecture Breakdown (Time-sliced), Instructional Media, Student Activities, and Assessment Questions.',
    placeholderInputs: ['Course Name & Code', 'Topic Title', 'Target Class / Semester', 'Duration (Hours)'],
    tags: ['faculty', 'lesson plan', 'teaching', 'syllabus'],
    iconName: 'BookMarked',
    isPopular: true,
    estimatedTime: '25s',
  },
  {
    id: 'ft-02',
    name: 'Question Paper',
    category: 'Faculty Templates',
    description: 'Formal examination question paper with Bloom’s taxonomy levels, marks distribution, and section splits.',
    suggestedTone: 'Formal & Precise',
    suggestedLength: '2-4 pages',
    promptInstructions: 'Generate a balanced examination Question Paper specifying Institution Name, Subject, Time Allowed, Max Marks, Instructions, Part-A (Short Answer), Part-B (Long Answer), and Course Outcome (CO) mapping.',
    placeholderInputs: ['Subject Code & Name', 'Exam Type (Mid-term / End-sem)', 'Max Marks', 'Units Covered'],
    tags: ['question paper', 'exam', 'test', 'faculty'],
    iconName: 'FileSpreadsheet',
    isPopular: true,
    estimatedTime: '30s',
  },
  {
    id: 'ft-03',
    name: 'NAAC Documentation',
    category: 'Faculty Templates',
    description: 'Standard NAAC accreditation quality report for criteria compliance and department documentation.',
    suggestedTone: 'Formal & Compliance-Oriented',
    suggestedLength: '6-10 pages',
    promptInstructions: 'Construct NAAC Accreditation Documentation covering Criterion Objectives, Metric Proof Summaries, Data Verification Tables, Departmental Accomplishments, Best Practices, and Continuous Improvement Initiatives.',
    placeholderInputs: ['Department Name', 'Criterion Number / Title', 'Academic Year'],
    tags: ['naac', 'accreditation', 'quality', 'faculty'],
    iconName: 'ShieldCheck',
    isPopular: true,
    estimatedTime: '45s',
  },
  {
    id: 'ft-04',
    name: 'Rubrics for Project Evaluation',
    category: 'Faculty Templates',
    description: 'Detailed evaluation matrix for grading student projects, presentations, and lab work.',
    suggestedTone: 'Objective & Structured',
    suggestedLength: '2-3 pages',
    promptInstructions: 'Format a comprehensive Grading Rubrics Table specifying Criteria (e.g., Problem Understanding, Architecture, Code Quality, Demo, Q&A), Performance Levels (Excellent, Good, Average, Poor), and Weightages.',
    placeholderInputs: ['Course / Project Type', 'Max Marks', 'Evaluation Panel Names'],
    tags: ['rubrics', 'grading', 'evaluation', 'marks'],
    iconName: 'CheckSquare',
    estimatedTime: '25s',
  },
  {
    id: 'ft-05',
    name: 'Grant Proposal',
    category: 'Faculty Templates',
    description: 'Academic research grant funding proposal for government bodies (DST, AICTE, UGC, SERB).',
    suggestedTone: 'Persuasive & Academic',
    suggestedLength: '8-15 pages',
    promptInstructions: 'Draft a competitive Research Grant Proposal containing Project Title, Principal Investigator Details, Executive Summary, Scientific Rationale, Work Plan & Methodology, Budget Breakdown (Equipment, Manpower, Travel), and Expected Impact.',
    placeholderInputs: ['Project Title', 'Funding Agency Name', 'Estimated Budget', 'Duration (Years)'],
    tags: ['grant', 'funding', 'research', 'dst', 'aicte'],
    iconName: 'Coins',
    isPopular: true,
    estimatedTime: '50s',
  },

  // ==========================================
  // CATEGORY 3: BUSINESS TEMPLATES (45 Templates)
  // ==========================================
  {
    id: 'bt-01',
    name: 'Business Proposal',
    category: 'Business Templates',
    description: 'High-converting client proposal outlining scope of work, deliverables, timeline, and pricing options.',
    suggestedTone: 'Persuasive & Executive',
    suggestedLength: '4-8 pages',
    promptInstructions: 'Draft a commercial Business Proposal containing Executive Summary, Client Problem & Requirements, Proposed Solution & Deliverables, Project Phases & Timeline, Team Profiles, Pricing Matrix, Terms & Acceptance.',
    placeholderInputs: ['Client Name', 'Project Title', 'Budget / Fee Structure', 'Key Milestones'],
    tags: ['business proposal', 'client pitch', 'sales', 'contract'],
    iconName: 'Briefcase',
    isPopular: true,
    estimatedTime: '35s',
  },
  {
    id: 'bt-02',
    name: 'Business Plan',
    category: 'Business Templates',
    description: 'Comprehensive investor-ready business plan covering market analysis, business model, and financial projections.',
    suggestedTone: 'Strategic & Professional',
    suggestedLength: '10-20 pages',
    promptInstructions: 'Generate a full Business Plan including Company Overview, Mission & Vision, Industry Analysis, Target Market & Competitors, Product/Service Offerings, Marketing & Sales Strategy, Operational Plan, and 3-Year Financial Forecasts.',
    placeholderInputs: ['Company Name', 'Industry Sector', 'Target Market', 'Funding Sought'],
    tags: ['business plan', 'startup', 'investor', 'strategy'],
    iconName: 'TrendingUp',
    isPopular: true,
    estimatedTime: '55s',
  },
  {
    id: 'bt-03',
    name: 'Product Requirements Document (PRD)',
    category: 'Business Templates',
    description: 'Standard product management document defining feature requirements, user flows, and success metrics.',
    suggestedTone: 'Clear & Actionable',
    suggestedLength: '5-10 pages',
    promptInstructions: 'Create an industry-standard Product Requirements Document (PRD) detailing Product Vision, User Personas, User Stories, Acceptance Criteria, Functional Requirements, Technical Constraints, and Key Performance Indicators (KPIs).',
    placeholderInputs: ['Product Feature Name', 'Target Persona', 'Success Metric (e.g. Conversion rate)'],
    tags: ['prd', 'product management', 'features', 'agile'],
    iconName: 'Compass',
    isPopular: true,
    estimatedTime: '40s',
  },
  {
    id: 'bt-04',
    name: 'Non-Disclosure Agreement (NDA)',
    category: 'Business Templates',
    description: 'Standard mutual or one-way non-disclosure agreement for confidential business information.',
    suggestedTone: 'Legal & Authoritative',
    suggestedLength: '3-5 pages',
    promptInstructions: 'Draft a legally sound Non-Disclosure Agreement (NDA) defining Disclosing & Receiving Parties, Definition of Confidential Information, Exclusions, Obligations of Secrecy, Term & Termination, Governing Law, and Signatures.',
    placeholderInputs: ['Party A Name', 'Party B Name', 'Jurisdiction / State', 'Duration (Years)'],
    tags: ['nda', 'legal', 'agreement', 'confidentiality'],
    iconName: 'ShieldAlert',
    isPopular: true,
    estimatedTime: '30s',
  },
  {
    id: 'bt-05',
    name: 'Invoice / Billing Quotation',
    category: 'Business Templates',
    description: 'Professional commercial quotation or invoice template with itemized costs and payment terms.',
    suggestedTone: 'Formal & Clear',
    suggestedLength: '1-2 pages',
    promptInstructions: 'Format a commercial Invoice / Quotation featuring Company Header, Invoice Number, Bill To Client Details, Itemized Line Items (Description, Qty, Unit Price, Tax, Subtotal), Payment Terms, and Bank Wire Details.',
    placeholderInputs: ['Client Name & Address', 'Line Items & Amounts', 'Payment Terms (e.g. Net 30)'],
    tags: ['invoice', 'quotation', 'billing', 'finance'],
    iconName: 'Receipt',
    isPopular: true,
    estimatedTime: '20s',
  },

  // ==========================================
  // CATEGORY 4: ATS RESUME BUILDER (20 Templates)
  // ==========================================
  {
    id: 'ats-01',
    name: 'ATS Software Engineer Resume',
    category: 'ATS Resume Builder',
    description: 'Optimized high-pass rate ATS resume tailored for software development and engineering roles.',
    suggestedTone: 'Impactful & Action-Oriented',
    suggestedLength: '1-2 pages',
    promptInstructions: 'Construct a single/two-page ATS-optimized Software Engineer Resume featuring Professional Summary, Core Tech Stack (Languages, Frameworks, Cloud), Work Experience with quantified metrics (STAR method), Projects, and Education.',
    placeholderInputs: ['Full Name', 'Target Job Title (e.g. Senior Full Stack Engineer)', 'Years Experience', 'Key Tech Stack'],
    tags: ['ats', 'resume', 'software engineer', 'developer', 'tech'],
    iconName: 'FileCheck2',
    isPopular: true,
    estimatedTime: '25s',
  },
  {
    id: 'ats-02',
    name: 'ATS Executive Resume',
    category: 'ATS Resume Builder',
    description: 'Executive resume template for VP, Director, C-suite, and senior management candidates.',
    suggestedTone: 'Leadership & Strategic',
    suggestedLength: '2 pages',
    promptInstructions: 'Draft an ATS-tailored Executive Resume detailing Executive Profile, Core Competencies (P&L Management, Global Strategy), Key Career Milestones, Leadership Experience with revenue/growth metrics, and Board/Education credentials.',
    placeholderInputs: ['Full Name', 'Executive Title (e.g. Chief Technology Officer)', 'Industry', 'Key Achievements'],
    tags: ['executive resume', 'cto', 'ceo', 'director', 'ats'],
    iconName: 'UserCheck',
    isPopular: true,
    estimatedTime: '30s',
  },
  {
    id: 'ats-03',
    name: 'ATS Data Scientist Resume',
    category: 'ATS Resume Builder',
    description: 'Data science and AI engineer resume emphasizing ML models, data pipelines, and business impacts.',
    suggestedTone: 'Technical & Analytical',
    suggestedLength: '1-2 pages',
    promptInstructions: 'Create a Data Science ATS Resume featuring Skills Matrix (Python, PyTorch, SQL, MLOps), Work Experience showcasing model accuracy & ROI metrics, Research/Projects, and Education.',
    placeholderInputs: ['Full Name', 'Target Role', 'Key Frameworks & Models'],
    tags: ['data science', 'ai', 'machine learning', 'resume'],
    iconName: 'BarChart3',
    estimatedTime: '25s',
  },
  {
    id: 'ats-04',
    name: 'ATS Fresher / Graduate Resume',
    category: 'ATS Resume Builder',
    description: 'Entry-level ATS resume template highlighting academic achievements, internships, and core projects.',
    suggestedTone: 'Enthusiastic & Professional',
    suggestedLength: '1 page',
    promptInstructions: 'Construct an entry-level ATS Resume for fresh graduates highlighting Career Objective, Technical & Soft Skills, Key Academic Projects, Internship Experience, Certifications, and Education.',
    placeholderInputs: ['Graduate Name', 'Degree / Branch', 'Key Projects', 'Target Entry Role'],
    tags: ['fresher', 'graduate', 'intern', 'entry level'],
    iconName: 'GraduationCap',
    isPopular: true,
    estimatedTime: '20s',
  },

  // ==========================================
  // CATEGORY 5: LETTERS (15 Templates)
  // ==========================================
  {
    id: 'lt-01',
    name: 'Formal Resignation Letter',
    category: 'Letters',
    description: 'Polite and professional employment resignation notice with last working day details.',
    suggestedTone: 'Professional & Gracious',
    suggestedLength: '1 page',
    promptInstructions: 'Write an official Resignation Letter specifying Intention to Resign, Last Working Day, Expressing Gratitude for Opportunities, Offering Support during Transition, and Contact Information.',
    placeholderInputs: ['Employee Name', 'Company Name', 'Job Title', 'Notice Period / Last Day'],
    tags: ['resignation', 'letter', 'job', 'hr'],
    iconName: 'MailX',
    isPopular: true,
    estimatedTime: '15s',
  },
  {
    id: 'lt-02',
    name: 'Job Application Cover Letter',
    category: 'Letters',
    description: 'Compelling cover letter matching candidate qualifications to employer job requirements.',
    suggestedTone: 'Persuasive & Professional',
    suggestedLength: '1 page',
    promptInstructions: 'Draft a tailored Cover Letter addressing Hiring Manager, stating Role applied for, highlighting Top 3 Relevant Achievements, demonstrating Knowledge of the Company, and inviting a Conversation.',
    placeholderInputs: ['Applicant Name', 'Target Company', 'Target Job Title', 'Key Strengths'],
    tags: ['cover letter', 'job application', 'career'],
    iconName: 'Send',
    isPopular: true,
    estimatedTime: '20s',
  },
  {
    id: 'lt-03',
    name: 'Recommendation Letter',
    category: 'Letters',
    description: 'Strong letter of endorsement for a student or employee written by a mentor or supervisor.',
    suggestedTone: 'Endorsing & Professional',
    suggestedLength: '1-2 pages',
    promptInstructions: 'Write a Letter of Recommendation (LOR) detailing Relationship with Applicant, Duration Known, Key Technical/Personal Strengths observed with specific examples, and Unreserved Recommendation.',
    placeholderInputs: ['Recommender Name & Title', 'Applicant Name', 'Program / Position Applied For'],
    tags: ['recommendation', 'lor', 'reference'],
    iconName: 'Award',
    isPopular: true,
    estimatedTime: '20s',
  },

  // ==========================================
  // CATEGORY 6: GOVERNMENT (10 Templates)
  // ==========================================
  {
    id: 'gov-01',
    name: 'RTI Application Letter',
    category: 'Government',
    description: 'Standard Right to Information (RTI) application format for public department inquiry.',
    suggestedTone: 'Formal & Statutory',
    suggestedLength: '1-2 pages',
    promptInstructions: 'Format an official Right to Information (RTI) Application under Section 6(1) of the RTI Act specifying Public Information Officer (PIO) Address, Specific Particulars of Information Sought, Application Fee Details, and Applicant Contact Information.',
    placeholderInputs: ['Applicant Name', 'Public Authority / Department', 'Information Requested Details'],
    tags: ['rti', 'government', 'application', 'india'],
    iconName: 'Building',
    isPopular: true,
    estimatedTime: '25s',
  },
  {
    id: 'gov-02',
    name: 'Police Complaint Letter',
    category: 'Government',
    description: 'Formal written complaint letter to police station for lost items, theft, or cyber fraud.',
    suggestedTone: 'Factual & Urgent',
    suggestedLength: '1 page',
    promptInstructions: 'Draft a Police Complaint Letter addressed to Station House Officer (SHO) detailing Date/Time of Incident, Specific Incident Breakdown (e.g. Lost document/phone/cyber crime), Suspect Info (if any), and Formal Request for FIR/CSR ACK.',
    placeholderInputs: ['Complainant Name', 'Police Station Location', 'Incident Type & Date'],
    tags: ['police complaint', 'fir', 'government', 'lost item'],
    iconName: 'ShieldAlert',
    isPopular: true,
    estimatedTime: '20s',
  },

  // ==========================================
  // CATEGORY 7: PERSONAL (10 Templates)
  // ==========================================
  {
    id: 'per-01',
    name: 'Travel Itinerary & Trip Planner',
    category: 'Personal',
    description: 'Comprehensive day-by-day travel itinerary with flights, stays, activities, and budget tracker.',
    suggestedTone: 'Organized & Inspiring',
    suggestedLength: '2-4 pages',
    promptInstructions: 'Generate a detailed Travel Itinerary featuring Trip Summary, Flight/Train Schedule, Hotel Reservations, Day-by-Day Schedule Breakdown (Morning, Afternoon, Evening), Packing Checklist, and Emergency Contacts.',
    placeholderInputs: ['Destination', 'Trip Duration (Days)', 'Travelers', 'Key Interests'],
    tags: ['travel', 'itinerary', 'vacation', 'trip planner'],
    iconName: 'Compass',
    isPopular: true,
    estimatedTime: '25s',
  },
  {
    id: 'per-02',
    name: 'Personal Budget & Expense Plan',
    category: 'Personal',
    description: 'Monthly personal budget allocation framework following 50/30/20 rule.',
    suggestedTone: 'Structured & Practical',
    suggestedLength: '2 pages',
    promptInstructions: 'Structure a Monthly Personal Financial Plan outlining Income Sources, Fixed Expenses (Rent, Utilities), Variable Needs, Savings & Investment Targets (50/30/20 Rule breakdown), and Debt Paydown Schedule.',
    placeholderInputs: ['Monthly Income', 'Primary Expenses', 'Savings Goal'],
    tags: ['budget', 'personal finance', 'savings', 'expenses'],
    iconName: 'Wallet',
    isPopular: true,
    estimatedTime: '20s',
  },
];
